name: Smoke Test Docker Image

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
on:
  push:
    branches:
      - main
jobs:
    build:
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
      - uses: actions/checkout@master
      - uses: jakejarvis/hugo-build-action@master  # ...or replace 'master' with a full version tag, such as: v0.64.1
        with:
          args: --minify --buildDrafts
      - uses: actions/upload-artifact@master
        with:
          name: website
          path: './public'
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
            folder: public      